production:
  postgres:
    connection:
      host: 172.16.0.184
      port: 5432
      username: game
      password: 123dss9393weqw
      database: PawaBox_Ke


# 0 0 * * * psql -U your_user -d PawaBox_Ke -c "INSERT INTO core.kpi (date) VALUES (now());"

